#DANCEVIDEOS
DanceVideo.create(title: "Waves", category: "hip/hop", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=VCX1mNfTnx0" )
DanceVideo.create(title: "Shuffle steps", category: "hip/hop", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=29pQw2e1Ugg")
DanceVideo.create(title: "Isolations", category: "hip/hop", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=Xgsk7yvSiPg")
DanceVideo.create(title: "Turns", category: "ballet", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=FYSHg3SajIY")
DanceVideo.create(title: "Barre", category: "ballet", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=ZSIfgTOowYk")
DanceVideo.create(title: "Line dance", category: "square dance", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=bZzmMlMUhOs")
DanceVideo.create(title: "Merengue", category: "merengue", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=amuqoK53QVU")
DanceVideo.create(title: "Salsa basic step", category: "salsa", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=wV8cDpJa2f4")
DanceVideo.create(title: "Tap steps", category: "tap dance", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=LH_EyxsupRE")
DanceVideo.create(title: "Waltz box step", category: "ballroom dance", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=NBKTN6c_MEQ")
DanceVideo.create(title: "Six step footwork", category: "breakdance", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=zPdQ1gN7Ngo")
DanceVideo.create(title: "Fixed point", category: "hip/hop", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=Z2mqOMcQa8c")
DanceVideo.create(title: "Salsa basic step", category: "salsa", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=C4MAFLeWY7c")
DanceVideo.create(title: "Basic tap step", category: "tap dance", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=HZruz8wO0g8")
DanceVideo.create(title: "Rumba Routine", category: "ballroom dance", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=0NcmFNl7sXc")
DanceVideo.create(title: "Intermediate step combination", category: "tap dance", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=MPW-geOjDG4")
DanceVideo.create(title: "Six count footwork", category: "swing dance", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=-FvsnqL124Q")
DanceVideo.create(title: "Toprock", category: "breakdance", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=WCGmegTpOFU")
DanceVideo.create(title: "Advanced step combination", category: "tap dance", difficulty_level: "advanced", url: "https://www.youtube.com/watch?v=7j8DS1YoQwQ")
DanceVideo.create(title: "Lindy Hop moves", category: "swing dance", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=RohnBhx2rOs")
DanceVideo.create(title: "How to windmill", category: "breakdance", difficulty_level: "advanced", url: "https://www.youtube.com/watch?v=0dB7JjpBMtI")
DanceVideo.create(title: "Count basic and jockey", category: "swing dance", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=epuXyK0C_bk")
DanceVideo.create(title: "How to Swipe", category: "breakdance", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=14WfVM98qGA")
DanceVideo.create(title: "Six count tuck turn", category: "swing dance", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=Rr-PrzCLmZQ")
DanceVideo.create(title: "Basic foxtrot step", category: "ballroom dance", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=LQCDkaDaMjI")
DanceVideo.create(title: "Advanced lindy hops", category: "swing dance", difficulty_level: "advanced", url: "https://www.youtube.com/watch?v=CAkLubN9daU")
DanceVideo.create(title: "Basic jazz moves", category: "jazz", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=GDHWUqMQpgM")
DanceVideo.create(title: "Haka tutorial", category: "haka", difficulty_level: "", url: "https://www.youtube.com/watch?v=p5cHElD5cf8")
DanceVideo.create(title: "Disco Funk", category: "disco", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=cgDppkLnImI")
DanceVideo.create(title: "Basic shuffle", category: "shuffle", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=pddp8OLi7lo")
DanceVideo.create(title: "Three intermediate steps", category: "shuffle", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=9aE35W_SnTU")
DanceVideo.create(title: "Tutting", category: "hip/hop", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=lrluSO-Qs0E")
DanceVideo.create(title: "Body waves", category: "hip/hop", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=8BRogKK6q-c")
DanceVideo.create(title: "Feet Position", category: "ballet", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=hr7Q9ewlkzE")
DanceVideo.create(title: "Popping", category: "hip/hop", difficulty_level: "beginner", url: "https://www.youtube.com/watch?v=UlXuMDaUE0E")
DanceVideo.create(title: "Air Walk", category: "hip/hop", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=y0mfNWKBQp0")
DanceVideo.create(title: "Pin/Knee drop", category: "hip/hop", difficulty_level: "intermediate", url: "https://www.youtube.com/watch?v=KZhRZODwCes")
DanceVideo.create(title: "Body waves", category: "hip/hop", difficulty_level: "advanced", url: "https://www.youtube.com/watch?v=AYUXBDAXIzg")

User.create(name: "June", username: "jk91", password: "password")

